/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        Clock: typeof import('./src/components/clock/index.vue')['default']
        ElButton: typeof import('element-plus/es')['ElButton']
        ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
        ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
        ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
        ElContainer: typeof import('element-plus/es')['ElContainer']
        ElHeader: typeof import('element-plus/es')['ElHeader']
        ElInput: typeof import('element-plus/es')['ElInput']
        ElMain: typeof import('element-plus/es')['ElMain']
        ElOption: typeof import('element-plus/es')['ElOption']
        ElRadio: typeof import('element-plus/es')['ElRadio']
        ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
        ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
        ElSelect: typeof import('element-plus/es')['ElSelect']
        ElSlider: typeof import('element-plus/es')['ElSlider']
        ElSwitch: typeof import('element-plus/es')['ElSwitch']
        ElTooltip: typeof import('element-plus/es')['ElTooltip']
        Flipper: typeof import('./src/components/clock/flipper.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        SvgIcon: typeof import('./src/components/svgIcon/index.vue')['default']
    }
}
