/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        CCard: typeof import('./src/components/cCard/index.vue')['default']
        Clock: typeof import('./src/components/clock/index.vue')['default']
        ColoredCard: typeof import('./src/components/coloredCard/index.vue')['default']
        CommandPalette: typeof import('./src/components/commandPalette/index.vue')['default']
        CommandPaletteOption: typeof import('./src/components/commandPalette/commandPaletteOption.vue')['default']
        Components: typeof import('./src/components/index.vue')['default']
        ElButton: typeof import('element-plus/es')['ElButton']
        ElCol: typeof import('element-plus/es')['ElCol']
        ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
        ElDialog: typeof import('element-plus/es')['ElDialog']
        ElIcon: typeof import('element-plus/es')['ElIcon']
        ElInput: typeof import('element-plus/es')['ElInput']
        ElRow: typeof import('element-plus/es')['ElRow']
        ElTooltip: typeof import('element-plus/es')['ElTooltip']
        FavoriteBtn: typeof import('./src/components/favoriteBtn/index.vue')['default']
        FavoriteButton: typeof import('./src/components/FavoriteButton.vue')['default']
        Flipper: typeof import('./src/components/clock/flipper.vue')['default']
        Header: typeof import('./src/components/header/index.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        SvgIcon: typeof import('./src/components/svgIcon/index.vue')['default']
        ToolCard: typeof import('./src/components/toolCard/index.vue')['default']
    }
}
