catalogMode: prefer

cleanupUnusedCatalogs: true

shellEmulator: true

trustPolicy: no-downgrade
packages:
  - apps/*
  - packages/*
catalog:
  axios: ^1.13.2
  color-gradient-picker-vue3: ^3.1.6
  typescript: ^5.9.3
  vite: ^7.2.6
  vite-plugin-dts: 4.5.4
